name: Create a new blog post

on:
  workflow_dispatch:
    inputs:
      post_title:
        description: 'Define blog post title'
        required: true
        default: ''

jobs:
  setup-new-post-branch:
    name: "Init creation of article ${{ github.event.inputs.post_title }}"
    runs-on: ubuntu-22.04

    permissions:
      contents: write # required for action-create-branch

    steps:
      - name: "Sanitize branch name"
        id: sanitized_branch_name
        uses: yeouchien/sanitize-branch-name-action@v1
        with:
          branch-name: 'post/${{ inputs.post_title }}'
      - name: "Create branch"
        uses: peterjgrainger/action-create-branch@v2.2.0
        if: ${{ inputs.post_title }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.sanitized_branch_name.outputs }}
