name: Create a new blog post

on:
  workflow_dispatch:
    inputs:
      post_title:
        description: 'Define blog post title'
        required: true
        default: ''

jobs:
  setup-new-post-branch:
    name: "Init creation of article ${{ github.event.inputs.post_title }}"
    runs-on: ubuntu-22.04

    permissions:
      contents: write # required for action-create-branch

    steps:
      - name: "Sanitize branch name"
        id: git_sanitizer
        uses: yeouchien/sanitize-branch-name-action@v1
        with:
          branch-name: '${{ inputs.post_title }}'
      - name: "Create branch"
        uses: peterjgrainger/action-create-branch@v2.2.0
        if: ${{ inputs.post_title }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'post/${{ steps.git_sanitizer.outputs.sanitized-branch-name }}'
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: "Prepare draft article"
        uses: actions/checkout@v3
        with:
          ref: post/${{ steps.git_sanitizer.outputs.sanitized-branch-name }}
      - run: |
          cd /_posts
          touch "${{ steps.date.outputs.date }}-${{ steps.git_sanitizer.outputs.sanitized-branch-name }}.md"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated content"
          git push
