name: Create a new blog post

on:
  workflow_dispatch:
    inputs:
      post_title:
        description: 'Define blog post title'
        required: true
        default: ''

jobs:
  setup-new-post-branch:
    name: "Init creation of article ${{ github.event.inputs.post_title }}"
    runs-on: ubuntu-22.04

    permissions:
      contents: write # required for action-create-branch

    steps:
      - name: "Sanitize branch name"
        id: git_sanitizer
        uses: yeouchien/sanitize-branch-name-action@v1
        with:
          branch-name: '${{ inputs.post_title }}'
      - name: "Create branch"
        uses: peterjgrainger/action-create-branch@v2.2.0
        if: ${{ inputs.post_title }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'post/${{ steps.git_sanitizer.outputs.sanitized-branch-name }}'
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: "Prepare draft article"
        uses: actions/checkout@v3
        with:
          ref: post/${{ steps.git_sanitizer.outputs.sanitized-branch-name }}
#       - run: |
#           touch _posts/${{ steps.date.outputs.date }}-${{ steps.git_sanitizer.outputs.sanitized-branch-name }}.md
          
#           git config user.name github-actions
#           git config user.email github-actions@github.com
#           git add .
#           git commit -m "generated content"
#           git push

      - name: "Apply post template"
        uses: danielr1996/envsubst-action@1.0.0
        env:
          POST_TITLE_TPL: ${{ inputs.post_title }}
        with:
          input: .github/templates/post-template.md
          output: _posts/${{ steps.date.outputs.date }}-${{ steps.git_sanitizer.outputs.sanitized-branch-name }}.md
      - run: |
          cat _posts/${{ steps.date.outputs.date }}-${{ steps.git_sanitizer.outputs.sanitized-branch-name }}.md
      
      - name: "Push draft article"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: post/${{ steps.git_sanitizer.outputs.sanitized-branch-name }}
          commit_message: "Prepare blog post markdown file"
