name: Create a new blog post

on:
  workflow_dispatch:
    inputs:
      post_title:
        description: 'Define blog post title'
        required: true
        default: ''

jobs:
  setup-new-post-branch:
    runs-on: ubuntu-22.04

    steps:
      - name: "Dump inputs"
        run: |
        echo "post_title: ${{ github.event.inputs.post_title }}"
      - name: "Create branch"
        uses: peterjgrainger/action-create-branch@v2.2.0
        if: ${{ inputs.post_title }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'refs/head/post/${{ github.event.inputs.post_title }}'
          sha: ${{ github.sha }}
